# Generated by Django 3.2.4 on 2021-06-28 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'get_latest_by': 'id', 'ordering': ['id'], 'verbose_name': 'circle_person'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='name',
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Title', max_length=64, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AddField(
            model_name='person',
            name='allowsMessage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to='circle.Article'),
        ),
        migrations.AddField(
            model_name='person',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_circle_person_following_+', to='circle.Person'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
