# Generated by Django 3.2.5 on 2021-07-04 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Article', max_length=64, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=255),
        ),
    ]
