# Generated by Django 3.2.4 on 2021-06-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0002_auto_20210628_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'circle_person'},
        ),
    ]
