# Generated by Django 3.2.5 on 2021-07-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0002_auto_20210704_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
