# Generated by Django 3.2.5 on 2021-07-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0002_auto_20210705_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ph_no',
            field=models.BigIntegerField(unique=True),
        ),
    ]
