# Generated by Django 3.2.4 on 2021-06-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0005_alter_person_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='ph_no',
            field=models.BigIntegerField(unique=True),
        ),
    ]
