# Generated by Django 3.2.5 on 2021-07-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0005_auto_20210706_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(default='A Tag', max_length=255),
        ),
        migrations.AddField(
            model_name='tag',
            name='domain',
            field=models.CharField(default='General', max_length=64),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(default='Describe the article...', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
