# Generated by Django 3.2.5 on 2021-07-04 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0005_auto_20210704_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
