# Generated by Django 3.2.4 on 2021-06-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0006_auto_20210628_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='sold',
        ),
    ]
