# Generated by Django 3.2.5 on 2021-07-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0006_auto_20210708_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
    ]
