# Generated by Django 3.2.5 on 2021-07-10 19:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0010_auto_20210708_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='person',
            name='display',
            field=models.ManyToManyField(blank=True, related_name='display', to='circle.Article'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(default='A Tag', max_length=511),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('messages', models.ManyToManyField(blank=True, related_name='messages', to='circle.Message')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='circle.person')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='circle.person')),
            ],
        ),
    ]
