# Generated by Django 3.2.5 on 2021-07-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0011_auto_20210710_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='bought',
            new_name='purchased',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='person',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='person',
            name='following',
        ),
        migrations.AddField(
            model_name='person',
            name='carted',
            field=models.ManyToManyField(blank=True, related_name='carted', to='circle.Article'),
        ),
        migrations.AddField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_circle_person_friends_+', to='circle.Person'),
        ),
    ]
