# Generated by Django 3.2.5 on 2021-07-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0013_auto_20210716_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_ts',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='hu9h48reh98ruhid', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default='hu9h48reh98r', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='slug',
            field=models.SlugField(default='hu9h48reh98r', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profile',
            field=models.ImageField(blank=True, default='https://img.icons8.com/bubbles/100/000000/stormtrooper.png', upload_to='images/persons'),
        ),
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(default='hu9h48reh9', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='hu9h48r9', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to='images/articles'),
        ),
    ]
