# Generated by Django 3.2.5 on 2021-07-22 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0016_auto_20210718_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='circle.person'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='circle.person'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(default='Type a Message...', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile',
            field=models.ImageField(default='https://img.icons8.com/bubbles/100/000000/stormtrooper.png', upload_to='images/persons'),
        ),
    ]
