# Generated by Django 3.2.5 on 2021-07-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0019_auto_20210724_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id']},
        ),
    ]
