# Generated by Django 3.2.5 on 2021-07-28 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0021_auto_20210727_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='created_date',
            new_name='created_ts',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
        migrations.AddField(
            model_name='article',
            name='updated_ts',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='updated_ts',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='circle.person'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='circle.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='created_ts',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_ts',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_ts',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_ts',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(max_length=511),
        ),
        migrations.AlterField(
            model_name='tag',
            name='domain',
            field=models.CharField(max_length=64),
        ),
    ]
