# Generated by Django 3.2.5 on 2021-07-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0022_auto_20210728_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
