# Generated by Django 3.2.5 on 2021-07-30 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0025_alter_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(default='Describe the article...', max_length=800),
        ),
        migrations.AlterField(
            model_name='chat',
            name='left',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='left', to='circle.person'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='right',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='right', to='circle.person'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='circle.person'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='circle.person'),
        ),
    ]
