# Generated by Django 3.2.5 on 2021-08-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0026_auto_20210730_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='retreated',
            field=models.ManyToManyField(blank=True, related_name='retreated', to='circle.Article'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=255),
        ),
    ]
