# Generated by Django 3.2.5 on 2021-08-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0027_auto_20210801_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagz', to='circle.Tag'),
        ),
    ]
