# Generated by Django 3.2.5 on 2021-09-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0028_person_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='ptags', to='circle.Tag'),
        ),
    ]
