# Generated by Django 3.2.5 on 2021-11-18 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0029_alter_person_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=9, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
