# Generated by Django 3.1.2 on 2021-02-10 16:45

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('circle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to='auth.user')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(blank=True, max_length=64)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Not Preferred to say')], default='X', max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('ph_no', models.BigIntegerField()),
                ('bookmarked', models.ManyToManyField(blank=True, related_name='bookmarked', to='circle.Article')),
                ('bought', models.ManyToManyField(blank=True, related_name='purchased', to='circle.Article')),
                ('rented', models.ManyToManyField(blank=True, related_name='rented', to='circle.Article')),
                ('sold', models.ManyToManyField(blank=True, related_name='sold', to='circle.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive', to='circle.person')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send', to='circle.person')),
            ],
        ),
    ]
