"""
Django settings for marketplace project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os

from dotenv import load_dotenv

load_dotenv()

from pathlib import Path

# import sentry_sdk
# from sentry_sdk.integrations.django import DjangoIntegration

# import environ
# env = environ.Env()
# environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(('SECRET_KEY'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True #os.getenv('DEBUG', default=False)

ALLOWED_HOSTS = [os.getenv('ALLOWED_HOSTS'), '127.0.0.1']

# ADMINS
# ADMINS = [os.getenv(('ADMINS')]
ADMINS = [('Priyansh Bordia', 'priyanshbordia2@gmail.com')]

# Application definition

INSTALLED_APPS = [
    'circle.apps.CircleConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', 
	'django_extensions',
	'django_humanize',
	'humanize',
	'bootstrap4',
	'fontawesome_5',
	'django_autoslug',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
   	'whitenoise.middleware.WhiteNoiseMiddleware',
]

WHITENOISE_AUTOREFRESH = True

ROOT_URLCONF = 'marketplace.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'marketplace.wsgi.application'

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'


# Logging
# https://docs.djangoproject.com/en/3.2/topics/logging/

# LOGGING = {
# 	'version': 1,
# 	'disable_existing_loggers': False,
# 	'formatters': {
# 		'verbose': {
# 			'format': ("%(asctime)s [%(levelname)-8s] '(%(module)s.%(funcName)s)' :: %(message)s")
# 		},
# 		'simple': {
# 			'format': '%(levelname)s :: %(message)s'
# 		}
# 	},
# 	'handlers': {
# 		'file': {
# 			'level': 'DEBUG',
# 			'class': 'logging.FileHandler',
# 			'filename': 'logs/debug.log',
# 			'formatter': 'verbose'
# 		},
# 		'console': {
# 			'level': 'DEBUG',
# 			'class': 'logging.StreamHandler',
# 			'formatter': 'verbose'
# 		},
# 	},
# 	'loggers': {
# 		'django': {
# 			'handlers': ["file"],
# 			'level': 'DEBUG',
# 			'propagate': True,
# 		},
# 	},
# 	"root": {
# 		"level": "DEBUG", 
# 		"handlers": ["file"]
# 	},
# }


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },

    'development': {
        'ENGINE': os.getenv('DEV_ENGINE'),
        'NAME': os.getenv('DEV_DB_NAME'),
        'USER': os.getenv('DEV_DB_USER'),
        'PASSWORD': os.getenv('DEV_DB_PASSWORD'),
        'HOST': os.getenv('DEV_DB_HOST'),
        'PORT': os.getenv('DEV_DB_PORT'),
    },

    'production': {
        'ENGINE': os.getenv('ENGINE'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False #True

# Set for test to not send warnings


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, '/static'),
    os.path.join(BASE_DIR, 'circle/static'),
)


# Media Files
MEDIA_ROOT = os.path.join(BASE_DIR, 'circle/static/media')
MEDIA_URL =  '/media/'

#login redirection to homepage
LOGIN_REDIRECT_URL = 'home'

#logout redirection to homepage
LOGOUT_REDIRECT_URL = 'home'

#Send reset pass e-mails
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS')
DEFAULT_FROM_EMAIL = 'Team Baazaar <no-reply@baazaar.io>'


# sentry_sdk.init(
#     dsn=os.environ.get("SENTRY_DSN"),
#     integrations=[DjangoIntegration()],
#     environment="prod"
# )
